# Database
server:
  port: 8080
  servlet:
    context-path: /api


spring:
  data:
    mongodb:
      database: test_db
      port: 27017
      host: localhost
      auto-index-creation: true


# graphql
graphql:
  servlet:
    maxQueryDepth: 100
    exception-handlers-enabled: true
    tracingEnabled: false

# graphiql
graphiql:
  mapping: /graphiql
  endpoint:
    graphql: /graphql
    subscriptions: /subscriptions
  subscriptions:
    timeout: 30
    reconnect: false
  static:
    basePath: /
  enabled: true
  pageTitle: GraphiQL
  cdn:
    enabled: false
    version: 0.13.0
#  props:
#    resources:
#      query: graphiql/querymutation.graphql
#      variables: graphiql/variables.json
#    variables:

#      editorTheme: "solarized light"